{{- if .Values.app.queueWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel-helm.fullname" . }}-queue-worker
  labels:
    {{- include "laravel-helm.labels" . | nindent 4 }}
    pod-kind: queue-worker
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.app.queueWorker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel-helm.selectorLabels" . | nindent 6 }}
      pod-kind: queue-worker
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "laravel-helm.selectorLabels" . | nindent 8 }}
        pod-kind: queue-worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "laravel-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-queue-worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.repository }}/queue_worker:{{ .Values.app.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.pullPolicy | default "IfNotPresent" }}
          envFrom:
            - configMapRef:
                name: {{ include "laravel-helm.fullname" . }}-env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
