apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-helm.fullname" . }}
  labels:
    {{- include "laravel-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{ if eq .Values.app.web.web_server "roadrunner" }}
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{ end }}
  selector:
    {{- include "laravel-helm.selectorLabels" . | nindent 4 }}
    pod-kind: web
    
